SEO-3147 PHP Desc long too short
syncfusion-content/php-docs pull request #230
Opened 2023-01-27 14:44 UTC by Yvone-Atieno

Hi @Aishwarya-Ganesan ,

Please review the changes for PHP Desc long too short.

Regards,
Yvone.

2023-01-27 14:46 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3147-PHP-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/php-docs/1564/console)**

2023-02-01 09:03 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-3147-PHP-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/php-docs/1565/console)**

2023-02-01 09:12 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3147-PHP-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/php-docs/1565/console)**

2023-02-01 09:15 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3147-PHP-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/php-docs/1565/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/php-docs/1565/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/php-docs/1565/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/php-docs/1565/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/php-docs/1565/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/php-docs/1565/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/php-docs/1565/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-07 12:45 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3147-PHP-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/php-docs/1570/console)**

2023-02-07 12:46 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3147-PHP-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/php-docs/1570/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/php-docs/1570/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/php-docs/1570/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/php-docs/1570/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/php-docs/1570/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/php-docs/1570/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/php-docs/1570/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-08 12:41 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3147-PHP-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/php-docs/1571/console)**

2023-02-08 12:42 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3147-PHP-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/php-docs/1571/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/php-docs/1571/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/php-docs/1571/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/php-docs/1571/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/php-docs/1571/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/php-docs/1571/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/php-docs/1571/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-09 12:10 UTC, Aishwarya-Ganesan commented on PHP/DataManager/corsdatafetching.md
> +# CORS Data Fetching in Essential PHP DataManager
Remove Essential word.

2023-02-09 12:10 UTC, Aishwarya-Ganesan reviewed
Commented.

2023-02-09 12:24 UTC, Yvone-Atieno commented on PHP/DataManager/corsdatafetching.md
> +# CORS Data Fetching in Essential PHP DataManager
removed

2023-02-09 12:25 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3147-PHP-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/php-docs/1572/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/php-docs/1572/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/php-docs/1572/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/php-docs/1572/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/php-docs/1572/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/php-docs/1572/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/php-docs/1572/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-17 06:34 UTC, gowthamanthavasiyappan requested changes

2023-02-17 06:34 UTC, gowthamanthavasiyappan commented on PHP/Rating/Getting-Started.md
> +# Getting Started with Essential PHP Rating
Remove Essential word.

2023-02-17 06:34 UTC, gowthamanthavasiyappan commented on PHP/Ribbon/getting-started.md
> +# Getting Started with Essential PHP Ribbon
Remove Essential word.

2023-02-17 06:34 UTC, gowthamanthavasiyappan commented
Commented

2023-02-17 06:54 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3147-PHP-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/php-docs/1576/console)**

2023-02-17 06:55 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3147-PHP-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/php-docs/1576/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/php-docs/1576/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/php-docs/1576/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/php-docs/1576/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/php-docs/1576/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/php-docs/1576/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/php-docs/1576/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-17 07:10 UTC, gowthamanthavasiyappan approved these changes

2023-02-21 05:45 UTC, Aishwarya-Ganesan approved these changes
Changes are fine.

2023-02-21 05:45 UTC, merged